version: '3.8'

services:

  # Production / deployment services
  frontend:    &frontend
    profiles: ["production"]
    build:
      context: .
      dockerfile: ./scripts/docker/frontend.Dockerfile
    image: annot8_frontend:latest
    container_name: annot8_frontend

    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - ${FRONTEND_PORT:-80}:80

  migration:    &migration
    profiles: ["production"]
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    image: annot8_backend:latest
    container_name: annot8_migration

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py loaddata fixtures/labels
        python manage.py loaddata fixtures/users

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld

    depends_on: ["db"]

  backend:    &backend
    profiles: ["production"]
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    image: annot8_backend:latest
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_backend

    ports:
      - ${BACKEND_PORT:-8000}:8000

    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py runserver 0.0.0.0:8000


    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/media:/code/media

    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_started

  qcluster:    &qcluster
    profiles: ["production"]
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    image: annot8_backend:latest
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_queue

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py qcluster


    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/media:/code/media

    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_started

  db:     &db
    profiles: ["production"]
    env_file: [".env"]
    image: mariadb:latest
    container_name: annot8_db

    volumes:
      - /tmp/annot8/mysqld:/var/run/mysqld
      - ./backend/db:/var/lib/mysql

    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_HOST=${MYSQL_HOST}


  # Development services

  frontend.dev:
    profiles: ["dev"]
    env_file: [".env.local"]
    build:
      context: .
      dockerfile: ./scripts/docker/frontend.dev.Dockerfile
    image: annot8_frontend:dev
    container_name: annot8_frontend.dev

    ports:
      - ${FRONTEND_PORT:-8080}:8080

    volumes:
      - ./frontend/src:/code/src
      - ./frontend/public:/code/public
      - ./frontend/.env.docker.dev:/code/.env
      - ./frontend/babel.config.js:/code/babel.config.js
      - ./frontend/vue.config.js:/code/vue.config.js

  migration.dev:
    <<: *migration
    profiles: ["dev"]
    env_file: [".env.local"]

    build:
      context: .
      dockerfile: ./scripts/docker/backend.dev.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    image: annot8_backend:dev
    container_name: annot8_migration.dev
    depends_on: ["db.dev"]

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/annot8:/code/annot8
      - ./backend/annot8_api:/code/annot8_api
      - ./backend/manage.py:/code/manage.py
      - ./backend/fixtures:/code/fixtures

  backend.dev:
    <<: *backend
    profiles: ["dev"]
    env_file: [".env.local"]
    image: annot8_backend:dev
    container_name: annot8_backend.dev

    depends_on:
      migration.dev:
        condition: service_completed_successfully
      db.dev:
        condition: service_started

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/annot8:/code/annot8
      - ./backend/annot8_api:/code/annot8_api
      - ./backend/manage.py:/code/manage.py
      - ./backend/media.dev:/code/media


  db.dev:
    <<: *db
    container_name: annot8_db.dev
    profiles: ["dev"]
    env_file: [".env.local"]
    volumes:
      - /tmp/annot8/mysqld:/var/run/mysqld
      - ./backend/db.dev:/var/lib/mysql
