version: '3.8'

services:

  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    image: annot8_frontend:latest
    container_name: annot8_frontend

    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - ${FRONTEND_PORT:-80}:80

  migration:
    user: ${UID:-0}:${GID:-0}
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    image: annot8_backend:latest
    container_name: annot8_migration

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py loaddata fixtures/labels

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/mysql.cnf:/code/mysql.cnf

    depends_on:
      - db

  backend:
    user: ${UID:-0}:${GID:-0}
    image: annot8_backend:latest
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_backend

    ports:
      - ${BACKEND_PORT:-8000}:8000

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py runserver 0.0.0.0:8000

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/mysql.cnf:/code/mysql.cnf

    depends_on:
      - migration
      - db


  db:
    image: mariadb:latest
    container_name: annot8_db

    volumes:
      - /tmp/annot8/mysqld:/var/run/mysqld
      - ./backend/db:/var/lib/mysql

    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_HOST=${MYSQL_HOST}

    ports:
      - ${MYSQL_PORT}:3306
