services:

  frontend:
    build:
      context: .
      dockerfile: ./scripts/docker/frontend.Dockerfile
    image: annot8_frontend:latest
    container_name: annot8_frontend

    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

    ports:
      - ${FRONTEND_PORT:-80}:80

  migration:
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    image: annot8_backend:latest
    container_name: annot8_migration

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py migrate
        python manage.py loaddata fixtures/labels fixtures/users

    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/:/code/
      - /dev/null:/code/mysql.cnf

    depends_on: ["db"]

  backend:
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    image: annot8_nginx:latest
    build:
      context: .
      dockerfile: ./scripts/docker/backend.nginx.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_backend

    ports:
      - ${BACKEND_PORT:-8000}:80

    volumes:
      - annot8_uwsgi_data:/tmp/uwsgi/
      - annot8_web_static:/code/static/
      - annot8_web_static:/var/www/annot8/assets/
      - ./backend/media:/var/www/annot8/media/
    depends_on:
      uwsgi:
        condition: service_started

  uwsgi:
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    image: annot8_backend:latest
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_uwsgi

    environment:
      - FRONTEND_PORT=${FRONTEND_PORT:-8080}

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py collectstatic --noinput
        uwsgi --ini uwsgi.ini


    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/:/code/
      - /dev/null:/code/mysql.cnf
      - annot8_uwsgi_data:/tmp/uwsgi/
      - annot8_web_static:/code/static/
      - annot8_web_static:/var/www/annot8/assets/

    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_started

  qcluster:
    env_file: [".env"]
    user: ${UID:-0}:${GID:-0}
    image: annot8_backend:latest
    build:
      context: .
      dockerfile: ./scripts/docker/backend.Dockerfile
      args:
        GID: ${GID:-0}
        UID: ${UID:-0}

    container_name: annot8_queue

    command:
      - sh
      - -c
      - |
        python manage.py wait_for_db
        python manage.py qcluster


    volumes:
      - /tmp/annot8/mysqld:/run/mysqld
      - ./backend/:/code/
      - /dev/null:/code/mysql.cnf

    depends_on:
      migration:
        condition: service_completed_successfully
      db:
        condition: service_started
      redis:
        condition: service_started

  redis:
    env_file: [".env"]
    image: redis:latest
    container_name: annot8_redis

  db:
    env_file: [".env"]
    image: mariadb:latest
    container_name: annot8_db

    volumes:
      - /tmp/annot8/mysqld:/var/run/mysqld
      - ./backend/db:/var/lib/mysql

    environment:
      - MARIADB_DATABASE=${MYSQL_DATABASE}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_HOST=${MYSQL_HOST}




volumes:
  annot8_uwsgi_data:
  annot8_web_static:
