# Generated by Django 4.0.4 on 2022-05-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot8_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_folder',
            field=models.CharField(default='/tmp', max_length=255),
            preserve_default=False,
        ),
    ]
