# Generated by Django 4.0.7 on 2022-09-27 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('annot8_api', '0003_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaborators',
            field=models.ManyToManyField(related_name='collaborators', related_query_name='collaborators', to=settings.AUTH_USER_MODEL),
        ),
    ]
