# Generated by Django 4.1.2 on 2023-08-08 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('annot8_api', '0004_project_collaborators'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescribableObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='file',
            name='created',
        ),
        migrations.RemoveField(
            model_name='file',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='classifier',
            field=models.CharField(choices=[('Moth Classifier', 'Moth Classifier')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='detector',
            field=models.CharField(choices=[('Moth Detector', 'Moth Detector')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('top_1_label', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('described_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', related_query_name='prediction', to='annot8_api.describableobject')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Logit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.IntegerField()),
                ('logit', models.FloatField()),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('prediction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logit', related_query_name='logit', to='annot8_api.prediction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=255)),
                ('annotator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('confirmators', models.ManyToManyField(related_name='confirmators', related_query_name='confirmator', to=settings.AUTH_USER_MODEL)),
                ('described_object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation', related_query_name='annotation', to='annot8_api.describableobject')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='file',
            name='describableobject_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annot8_api.describableobject'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('describableobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='annot8_api.describableobject')),
                ('pipeline_generated', models.BooleanField(default=True)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('described_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bboxes', related_query_name='bbox', to='annot8_api.file')),
            ],
            options={
                'abstract': False,
            },
            bases=('annot8_api.describableobject',),
        ),
    ]
