# Generated by Django 4.1.13 on 2024-01-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot8_api', '0006_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='queued_task',
        ),
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(default='', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
