# Generated by Django 4.1.13 on 2024-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot8_api', '0007_remove_task_queued_task_task_task_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='nqueued',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
