# Generated by Django 4.1.13 on 2024-01-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annot8_api', '0008_task_nqueued'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
