# Generated by Django 4.1.13 on 2024-01-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labeltree', '0004_alter_label_taxonomic_rank'),
        ('annot8_api', '0010_alter_logit_label_alter_prediction_top_1_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labeltree.label'),
        ),
    ]
